/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** A cron schedule for executing a task at a specified interval.
  * @param cronExpr A cron expression for the task execution.
  * @param timezone The time zone for the schedule.
  */
case class CronSchedule(
    cronExpr: String,
    timezone: String
)
  
object CronSchedule {
  given encoderCronSchedule: Encoder[CronSchedule] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("cron_expr" -> t.cronExpr.asJson),
        Some("timezone" -> t.timezone.asJson)
      ).flatten
    }
  }
  given decoderCronSchedule: Decoder[CronSchedule] = Decoder.instance { c =>
    for {
      cronExpr <- c.downField("cron_expr").as[String]
      timezone <- c.downField("timezone").as[String]
    } yield CronSchedule(
      cronExpr = cronExpr,
      timezone = timezone
    )
  }
}

