/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** Database from share.
  * @param name A Snowflake object identifier.
  */
case class DatabaseFromShare(
    name: Option[String] = None
)
  
object DatabaseFromShare {
  given encoderDatabaseFromShare: Encoder[DatabaseFromShare] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.name.map(v => "name" -> v.asJson)
      ).flatten
    }
  }
  given decoderDatabaseFromShare: Decoder[DatabaseFromShare] = Decoder.instance { c =>
    for {
      name <- c.downField("name").as[Option[String]]
    } yield DatabaseFromShare(
      name = name
    )
  }
}

