/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** A column in the dynamic table
  * @param name Column name
  * @param datatype The data type for the column
  * @param comment Specifies a comment for the column
  */
case class DynamicTableColumn(
    name: String,
    datatype: Option[String] = None,
    comment: Option[String] = None
)
  
object DynamicTableColumn {
  given encoderDynamicTableColumn: Encoder[DynamicTableColumn] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("name" -> t.name.asJson),
        t.datatype.map(v => "datatype" -> v.asJson),
        t.comment.map(v => "comment" -> v.asJson)
      ).flatten
    }
  }
  given decoderDynamicTableColumn: Decoder[DynamicTableColumn] = Decoder.instance { c =>
    for {
      name <- c.downField("name").as[String]
      datatype <- c.downField("datatype").as[Option[String]]
      comment <- c.downField("comment").as[Option[String]]
    } yield DynamicTableColumn(
      name = name,
      datatype = datatype,
      comment = comment
    )
  }
}

