/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param systemgetServiceLogs 
  */
case class FetchServiceLogs200Response(
    systemgetServiceLogs: Option[String] = None
)
  
object FetchServiceLogs200Response {
  given encoderFetchServiceLogs200Response: Encoder[FetchServiceLogs200Response] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.systemgetServiceLogs.map(v => "system$get_service_logs" -> v.asJson)
      ).flatten
    }
  }
  given decoderFetchServiceLogs200Response: Decoder[FetchServiceLogs200Response] = Decoder.instance { c =>
    for {
      systemgetServiceLogs <- c.downField("system$get_service_logs").as[Option[String]]
    } yield FetchServiceLogs200Response(
      systemgetServiceLogs = systemgetServiceLogs
    )
  }
}

