/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param statement The executable SQL statement
  */
case class MessageContentSqlObject(
    statement: String
)
  
object MessageContentSqlObject {
  given encoderMessageContentSqlObject: Encoder[MessageContentSqlObject] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("statement" -> t.statement.asJson)
      ).flatten
    }
  }
  given decoderMessageContentSqlObject: Decoder[MessageContentSqlObject] = Decoder.instance { c =>
    for {
      statement <- c.downField("statement").as[String]
    } yield MessageContentSqlObject(
      statement = statement
    )
  }
}

