/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** Point of time indicating when a statement was executed.
  * @param statement Statement of the point of time.
  */
case class PointOfTimeStatement1(
    statement: Option[String] = None
)
  
object PointOfTimeStatement1 {
  given encoderPointOfTimeStatement1: Encoder[PointOfTimeStatement1] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.statement.map(v => "statement" -> v.asJson)
      ).flatten
    }
  }
  given decoderPointOfTimeStatement1: Decoder[PointOfTimeStatement1] = Decoder.instance { c =>
    for {
      statement <- c.downField("statement").as[Option[String]]
    } yield PointOfTimeStatement1(
      statement = statement
    )
  }
}

