/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param stream Creates the new stream at the same offset as the specified stream. 
  */
case class PointOfTimeStream(
    stream: Option[String] = None
)
  
object PointOfTimeStream {
  given encoderPointOfTimeStream: Encoder[PointOfTimeStream] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.stream.map(v => "stream" -> v.asJson)
      ).flatten
    }
  }
  given decoderPointOfTimeStream: Decoder[PointOfTimeStream] = Decoder.instance { c =>
    for {
      stream <- c.downField("stream").as[Option[String]]
    } yield PointOfTimeStream(
      stream = stream
    )
  }
}

