/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param offset Point of time identified by an offset in reference to the current time, such as `10 min`.
  */
case class PointOfTimeOffset(
    offset: String
)
  
object PointOfTimeOffset {
  given encoderPointOfTimeOffset: Encoder[PointOfTimeOffset] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("offset" -> t.offset.asJson)
      ).flatten
    }
  }
  given decoderPointOfTimeOffset: Decoder[PointOfTimeOffset] = Decoder.instance { c =>
    for {
      offset <- c.downField("offset").as[String]
    } yield PointOfTimeOffset(
      offset = offset
    )
  }
}

