/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param statement Statement of the point of time.
  */
case class PointOfTimeStatement(
    statement: String
)
  
object PointOfTimeStatement {
  given encoderPointOfTimeStatement: Encoder[PointOfTimeStatement] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("statement" -> t.statement.asJson)
      ).flatten
    }
  }
  given decoderPointOfTimeStatement: Decoder[PointOfTimeStatement] = Decoder.instance { c =>
    for {
      statement <- c.downField("statement").as[String]
    } yield PointOfTimeStatement(
      statement = statement
    )
  }
}

