/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}

import scala.collection.immutable.Seq

/** A primary key is the column or columns that contain values that uniquely identify each row in a table.
  */
case class PrimaryKey(
)
  
object PrimaryKey {
  given encoderPrimaryKey: Encoder[PrimaryKey] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
      ).flatten
    }
  }
  given decoderPrimaryKey: Decoder[PrimaryKey] = Decoder.instance { c =>
    Right(PrimaryKey())
  }
}

