/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}

import java.net.URI
import java.util.UUID
import scala.collection.immutable.Seq

/** 
  * @param code 
  * @param sqlState 
  * @param message 
  * @param statementHandle 
  * @param createdOn Timestamp that specifies when the statement execution started.‌ The timestamp is expressed in milliseconds since the epoch.‌
  * @param statementStatusUrl 
  * @param resultSetMetaData 
  * @param data Result set data.
  * @param stats 
  */
case class ResultSet(
    code: Option[String] = None,
    sqlState: Option[String] = None,
    message: Option[String] = None,
    statementHandle: Option[UUID] = None,
    createdOn: Option[Long] = None,
    statementStatusUrl: Option[URI] = None,
    resultSetMetaData: Option[ResultSetResultSetMetaData] = None,
    data: Option[Seq[Seq[String]]] = None,
    stats: Option[ResultSetStats] = None
)
  
object ResultSet {
  given encoderResultSet: Encoder[ResultSet] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.code.map(v => "code" -> v.asJson),
        t.sqlState.map(v => "sqlState" -> v.asJson),
        t.message.map(v => "message" -> v.asJson),
        t.statementHandle.map(v => "statementHandle" -> v.asJson),
        t.createdOn.map(v => "createdOn" -> v.asJson),
        t.statementStatusUrl.map(v => "statementStatusUrl" -> v.asJson),
        t.resultSetMetaData.map(v => "resultSetMetaData" -> v.asJson),
        t.data.map(v => "data" -> v.asJson),
        t.stats.map(v => "stats" -> v.asJson)
      ).flatten
    }
  }
  given decoderResultSet: Decoder[ResultSet] = Decoder.instance { c =>
    for {
      code <- c.downField("code").as[Option[String]]
      sqlState <- c.downField("sqlState").as[Option[String]]
      message <- c.downField("message").as[Option[String]]
      statementHandle <- c.downField("statementHandle").as[Option[UUID]]
      createdOn <- c.downField("createdOn").as[Option[Long]]
      statementStatusUrl <- c.downField("statementStatusUrl").as[Option[URI]]
      resultSetMetaData <- c.downField("resultSetMetaData").as[Option[ResultSetResultSetMetaData]]
      data <- c.downField("data").as[Option[Seq[Seq[String]]]]
      stats <- c.downField("stats").as[Option[ResultSetStats]]
    } yield ResultSet(
      code = code,
      sqlState = sqlState,
      message = message,
      statementHandle = statementHandle,
      createdOn = createdOn,
      statementStatusUrl = statementStatusUrl,
      resultSetMetaData = resultSetMetaData,
      data = data,
      stats = stats
    )
  }
}

