/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param `type` Type of the return, can be either DATATYPE or TABLE
  */
case class ReturnType1(
    `type`: String
)
  
object ReturnType1 {
  given encoderReturnType1: Encoder[ReturnType1] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        Some("type" -> t.`type`.asJson)
      ).flatten
    }
  }
  given decoderReturnType1: Decoder[ReturnType1] = Decoder.instance { c =>
    for {
      `type` <- c.downField("type").as[String]
    } yield ReturnType1(
      `type` = `type`
    )
  }
}

