/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param insertOnly Whether this stream is an insert only stream or not
  * @param pointOfTime 
  */
case class StreamSourceExternalTable(
    insertOnly: Option[Boolean] = None,
    pointOfTime: Option[PointOfTime1] = None
)
  
object StreamSourceExternalTable {
  given encoderStreamSourceExternalTable: Encoder[StreamSourceExternalTable] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.insertOnly.map(v => "insert_only" -> v.asJson),
        t.pointOfTime.map(v => "point_of_time" -> v.asJson)
      ).flatten
    }
  }
  given decoderStreamSourceExternalTable: Decoder[StreamSourceExternalTable] = Decoder.instance { c =>
    for {
      insertOnly <- c.downField("insert_only").as[Option[Boolean]]
      pointOfTime <- c.downField("point_of_time").as[Option[PointOfTime1]]
    } yield StreamSourceExternalTable(
      insertOnly = insertOnly,
      pointOfTime = pointOfTime
    )
  }
}

