/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** Schema for all the success responses returned by the server.
  * @param status Message returned by the server.
  */
case class SuccessResponse(
    status: Option[String] = None
)
  
object SuccessResponse {
  given encoderSuccessResponse: Encoder[SuccessResponse] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.status.map(v => "status" -> v.asJson)
      ).flatten
    }
  }
  given decoderSuccessResponse: Decoder[SuccessResponse] = Decoder.instance { c =>
    for {
      status <- c.downField("status").as[Option[String]]
    } yield SuccessResponse(
      status = status
    )
  }
}

