/** merged spec
  * merged spec
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package datoria.snowflake.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** When resizing a warehouse, you can use this parameter to block the return of the ALTER WAREHOUSE command until the resize has finished provisioning all its compute resources
  */
enum WarehouseWaitForCompletion(val value: String) {
  case `True` extends WarehouseWaitForCompletion("true")
  case `False` extends WarehouseWaitForCompletion("false")
}

object WarehouseWaitForCompletion {

  def withValueOpt(value: String): Option[WarehouseWaitForCompletion] = WarehouseWaitForCompletion.values.find(_.value == value)
  def withValue(value: String): WarehouseWaitForCompletion =
    withValueOpt(value).getOrElse(throw java.lang.IllegalArgumentException(s"WarehouseWaitForCompletion enum case not found: $value"))

  given decoderWarehouseWaitForCompletion: Decoder[WarehouseWaitForCompletion] = Decoder.decodeString.map(withValue)
  given encoderWarehouseWaitForCompletion: Encoder[WarehouseWaitForCompletion] = Encoder.encodeString.contramap[WarehouseWaitForCompletion](_.value)

}

