openapi: 3.0.1
info:
  title: Cortex Search REST API
  description: OpenAPI 3.0 specification for the Cortex Search REST API
  version: 0.1.0
  contact:
    name: Snowflake, Inc.
    url: https://snowflake.com
    email: support@snowflake.com
paths:
  /api/v2/databases/{database}/schemas/{schema}/cortex-search-services/{service_name}:query:
    post:
      summary: Query a Cortex Search Service.
      tags:
      - cortex-search-service
      description: Query a Cortex Search Service to get search results.
      operationId: queryCortexSearchService
      parameters:
      - $ref: common.yaml#/components/parameters/database
      - $ref: common.yaml#/components/parameters/schema
      - in: path
        name: service_name
        required: true
        schema:
          type: string
        description: The name of the Cortex Search Service.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          $ref: common.yaml#/components/responses/400BadRequest
        '401':
          $ref: common.yaml#/components/responses/401Unauthorized
        '403':
          $ref: common.yaml#/components/responses/403Forbidden
        '404':
          $ref: common.yaml#/components/responses/404NotFound
        '405':
          $ref: common.yaml#/components/responses/405MethodNotAllowed
        '409':
          $ref: common.yaml#/components/responses/409Conflict
        '500':
          $ref: common.yaml#/components/responses/500InternalServerError
        '503':
          $ref: common.yaml#/components/responses/503ServiceUnavailable
        '504':
          $ref: common.yaml#/components/responses/504GatewayTimeout
components:
  schemas:
    QueryRequest:
      type: object
      description: A search query and additional parameters for search.
      properties:
        query:
          description: Unstructured text query.
          type: string
        columns:
          description: List of columns to return.
          type: array
          items:
            type: string
        filter:
          description: Filter query.
          type: object
        limit:
          description: Max number of results to return.
          type: integer
          default: 10
        experimental:
          description: Opaque container for experimental features. You probably do
            not want to use this.
          type: object
          additionalProperties: true
      required:
      - query
      - columns
    QueryResponse:
      type: object
      description: Search results.
      properties:
        results:
          type: array
          description: List of result rows.
          items:
            type: object
            additionalProperties: true
            description: Map of column names to bytes.
        request_id:
          type: string
          description: ID of the request.
      required:
      - results
      - request_id
tags:
- name: cortex-search-service
